### PR TITLE
Remove HTTP server code

### PR DESCRIPTION
**Pull request by mneumann**
Related issues: #53

### CODE REVIEW

**Comment by mneumann** [comment]
I think something is wrong with CI or I missed something :/

**Comment by mfelsche** [comment]
There are server examples in the `examples` directory that are compiled as part of CI. Those need to be removed as well. Also check the makefile

**Comment by mneumann** [comment]
@mfelsche there was a `.gitignore` in the empty `httpserver`... Should work now

**Review by mfelsche — APPROVED** [review]

**Comment by mfelsche** [comment]
Thanks for your contribution! :) Deleted code is good code!

**Pull request merged**
