### PR TITLE
Fix net/http references in docs

### PR DESCRIPTION
**Pull request by bb010g**
Why are compiled docs stored in-tree? If they're being put on Pages, can't they be somewhere else and not clutter up the diffs here?

### CODE REVIEW

**Comment by mfelsche** [comment]
The html files are serving the github pages and are regenerated on each release. I wouldnt remove them, but we should configure github pages to get served from a differenz branch (gh-pages) and put the html files there.

**Comment by SeanTAllen** [comment]
I'd rather use a separate repo for compiled docs like we do with stdlib. I suspect @jemc would agree.

**Comment by mfelsche** [comment]
I think it is very convenient to have your docs being displayed as github pages. I agree that they can be disturbing being in a subdir in the tree. But i wouldnt start putting them in another repo. Just my opinion.

**Comment by SeanTAllen** [comment]
It doesn't prevent them from being displayed. It's our preferred method though rather than a magic branch.

**Comment by SeanTAllen** [comment]
@jemc and I already thunderdomed. He won. I want to keep our stuff consistent so... No magic branch.

**Comment by mfelsche** [comment]
Then a separate repo it is. I will merge once this is set up.

**Comment by jemc** [comment]
I would actually lean toward using the `gh-pages` approach. Did I say otherwise at some point?

**Comment by SeanTAllen** [comment]
Yes. Quite strongly against magic branches.

**Comment by mfelsche** [comment]
@jemc @SeanTAllen how do we go from here? I'd like to at least have sime kind of consensus or majority vote.

I am in favor of the `gh-pages` approach as it is basically no effort to get some docs online for your pony library and a good role model for other libs. Roast me.

**Comment by SeanTAllen** [comment]
I don't want to touch the Ponyc release process to make a change to this. I don't think its worth it. From that I'd prefer the separate repo being served off of netlify to keep things consistent but if you really want to do gh-pages for this I'm fine with that.

**Comment by jemc** [comment]
I'm not familiar enough with the ponyc / netlify integration, so pardon my ignorance here, but it looks like netlify has a `gh-pages` option: https://gohugobrasil.netlify.com/hosting-and-deployment/hosting-on-github/

**Comment by SeanTAllen** [comment]
No, that is a change and would involve touching the release process.

All of this git fun is what took a while to get working and that I don't want to change and break:

https://github.com/ponylang/ponyc/blob/master/.travis_commands.bash#L214

**Comment by SeanTAllen** [comment]
Here's the big question to me. What does the release process look like for this. If we can answer that, I'll take care of setting everything up.

So, what does it mean to release the HTTP library?

Are is it a tag on master? Tag on a release branch? If its tag based, I prefer it being on a release branch. Then from that branch we can trigger Travis doing... something...

That something would be

- generating documentation and putting "somewhere"
- ? is that it? probably yes for right now as folks would use stable to get the release or download from the releases page.

If we can agree on that, I'll work on setting it up.

I think for now, what I would attempt and we can see how it works out would be to store the generated documentation on the release branch. It kind of makes sense as it is an "easy" way to get at the documentation for a given release.

**Comment by mfelsche** [comment]
I think we already took the discussion to a place, that does not belong here. I will open issues for the leftover discussion for releasing and will merge this one. Thanks @bb010g !

**Comment by mfelsche** [comment]
I will also delete the github pages integration for now, and either move to the gh-pages branch or, when main.actor is finished first, link this one.

**Pull request merged**
